import {IncludeFunction, ROLE_ADMIN, ROLE_DEVELOPER, ROLE_USER} from '@valtimo/config';

export const menuItems = [
  {
    roles: [ROLE_USER],
    link: ['/'],
    title: 'Dashboard',
    iconClass: 'icon mdi mdi-view-dashboard',
    sequence: 0,
  },
  {
    roles: [ROLE_USER],
    title: 'Dossiers',
    iconClass: 'icon mdi mdi-layers',
    sequence: 1,
    children: [],
  },
  {
    roles: [ROLE_ADMIN],
    title: 'Objects',
    iconClass: 'icon mdi mdi-archive',
    sequence: 2,
    includeFunction: IncludeFunction.ObjectManagementEnabled,
  },
  {
    roles: [ROLE_USER],
    link: ['/tasks'],
    title: 'Tasks',
    iconClass: 'icon mdi mdi-check-all',
    sequence: 3,
  },
  {
    roles: [ROLE_ADMIN],
    link: ['/analysis'],
    title: 'Analysis',
    iconClass: 'icon mdi mdi-chart',
    sequence: 4,
  },
  {
    roles: [ROLE_ADMIN],
    title: 'Admin',
    iconClass: 'icon mdi mdi-tune',
    sequence: 4,
    children: [
      {title: 'Basics', textClass: 'text-dark font-weight-bold c-default', sequence: 1},
      {link: ['/processes'], title: 'Processes', sequence: 2},
      {link: ['/form-management'], title: 'Forms', sequence: 3},
      {link: ['/form-flow-management'], title: 'Form flows', sequence: 4},
      {link: ['/decision-tables'], title: 'Decision tables', sequence: 5},
      {link: ['/dossier-management'], title: 'Dossiers', sequence: 6},
      {link: ['/task-management'], title: 'Tasks', sequence: 7},
      {link: ['/connectors'], title: 'Connectors', sequence: 8},
      {link: ['/object-management'], title: 'Objects', sequence: 9},
      {link: ['/plugins'], title: 'Plugins', sequence: 10},
      {link: ['/process-links'], title: 'Process links', sequence: 11},
      {link: ['/dashboard-management'], title: 'Dashboard', sequence: 12},
      {link: ['/access-control'], title: 'Access Control', sequence: 13},
      {link: ['/translation-management'], title: 'Translations', sequence: 14},
      {link: ['/logging'], title: 'Logs', sequence: 15},
      {link: ['/notifications-api/notifications/failed'], title: 'Notifications', sequence: 16},
      {title: 'Other', textClass: 'text-dark font-weight-bold c-default', sequence: 17},
      {link: ['/case-migration'], title: 'Case migration (beta)', sequence: 18},
      {link: ['/process-migration'], title: 'Process migration', sequence: 19},
      {link: ['/choice-fields'], title: 'Choice fields', sequence: 20}
    ],
  },
  {
    roles: [ROLE_DEVELOPER],
    title: 'Development',
    iconClass: 'icon mdi mdi-code',
    sequence: 5,
    children: [
      {link: ['/swagger'], title: 'Swagger', iconClass: 'icon mdi mdi-dot-circle', sequence: 1},
    ],
  },
];
