POST {{objects_api_url}}
Authorization: Token {{token}}
Content-Crs: EPSG:4326
Content-Type: application/json

{
  "type": "{{objecttypes_api_url_alo}}",
  "record": {
    "index": 1,
    "typeVersion": "{{objecttypes_version}}",
    "data": {
      "bsn": "999991322",
      "data": {
        "your-details": {
          "naw": {
            "grAdresgegevens": {
              "plaats": "'s-Gravenhage",
              "straat": "Herengracht",
              "postcode": "2511 EG",
              "huisletter": "",
              "huisnummer": "1",
              "toevoeging": ""
            },
            "grPersoongegevens": {
              "Bsn": "999991322",
              "voornaam": "Celeste",
              "achternaam": "Avion",
              "voorletters": "C.",
              "voorvoegsels": "",
              "geboortedatum": "1960-12-29"
            }
          }
        },
        "alo-ioaw": {
          "grIoaw": {
            "geenRechtMeerWw": "NEE",
            "geenRechtMeerWga": "NEE",
            "gedeeltelijkArbeidsongeschikt": "NEE"
          }
        },
        "schulden": {
          "heeftSchulden": "JA",
          "grSchulden": {
            "hhgSchulden": [
              {
                "bijWieSchuld": "500",
                "uploadSchuld": [],
                "waardeSchuld": 4500
              }
            ]
          }
        },
        "alo-uitbetaling": {
          "ibanAanWie": "NEE"
        },
        "alo-uw-inkomsten": {
          "heeftInkomsten": "GEEN_INKOMSTEN"
        },
        "alo-reden-aanvraag": {
          "grIngangsdatum": {
            "bijstandsuitkeringEerderStarten": "NEE"
          },
          "grZelfstandige": {
            "wanneerGestopt": "2025-07-02",
            "redenZelfstandige": "EIGEN_BEDRIJF_ONVOLDOENDE_INKOMEN"
          },
          "waaromBijstandsuitkering": "EX_ZELFSTANDIGE"
        },
        "alo-uw-woonsituatie": {
          "grHuur": {
            "hoeveelHuur": 700,
            "huurcontract": "JA",
            "wieVerhuurder": "Eddard Stark",
            "contractOpUwNaam": "JA",
            "hoeveelHuurtoeslag": 500
          },
          "hoeWoontU": "ZELFSTANDIGE_HUURWONING",
          "grAndereBewoners": {
            "meerMensenOpAdres": "NEE"
          }
        },
        "alo-uw-beschikbaarheid": {
          "grBeschikbaarheid": {
            "onbetaald": "JA",
            "onbetaaldWerk": "Proteïne poeders mixen",
            "beschikbaarheid": 12,
            "organisatieOnbetaald": "Ga voor goud"
          }
        },
        "alo-gezinssamenstelling": {
          "partnerWoontBijU": "NEE",
          "thuiswonendeKinderen": "NEE"
        },
        "alo-aanvullende-gegevens": {
          "lieverPost": true,
          "grWoonsituatie": {
            "woonsituatie": "WAAR_IK_WOON"
          },
          "grNationaliteit": {
            "nationaliteitBezit": "NEDERLANDSE_NATIONALITEIT"
          },
          "grContactAanvraag": {
            "hulpAanvraag": "NEE"
          },
          "grNieuweContactgegevens": {
            "geenEmail": false,
            "emailAdres": "jouw.naam@ritense.com",
            "geenTelefoon": true
          }
        },
        "alo-bezittingen-en-schulden": {
          "grAandelen": {
            "hhgAannemelijkBelang": [
              {
                "waardeAandelen": 2.2,
                "uploadDagwaarde": []
              },
              {
                "waardeAandelen": 800,
                "uploadDagwaarde": []
              }
            ]
          },
          "grRekeningen": {
            "geenBankrekening": "GEEN_REKENING"
          },
          "grUwVermogen": {
            "welkVermogen": {
              "CRYPTO": false,
              "CARAVAN": false,
              "VAARTUIG": false,
              "CONTANTEN": false,
              "KOOPWONING": false,
              "MOTORVOERTUIG": false,
              "EEN_STUK_GROND": false,
              "OBLIGATIES_AANDELEN": true
            }
          }
        }
      },
      "type": "Verzoek AB DCM",
      "language_code": "nl",
      "submission_id": "b5c0c832-2d9b-4727-b638-7ce9c06810ed",
      "public_reference": "OF-{{$random.alphanumeric(8)}}"
    },
    "startAt": "2025-07-08",
    "registrationAt": "2025-07-08"
  }
}