POST {{objects_api_url}}
Authorization: Token {{token}}
Content-Crs: EPSG:4326
Content-Type: application/json

{
  "type": "{{objecttypes_api_url_alo}}",
  "record": {
    "index": 1,
    "typeVersion": "{{objecttypes_version}}",
    "data": {
      "bsn": "999991322",
      "data": {
        "your-details": {
          "naw": {
            "grAdresgegevens": {
              "plaats": "'s-Gravenhage",
              "straat": "Herengracht",
              "postcode": "2511 EG",
              "huisletter": "",
              "huisnummer": "1",
              "toevoeging": ""
            },
            "grPersoongegevens": {
              "Bsn": "999991322",
              "voornaam": "Celeste",
              "achternaam": "Avion",
              "voorletters": "C.",
              "voorvoegsels": "",
              "geboortedatum": "1960-12-29"
            }
          }
        },
        "alo-ioaw": {
          "grIoaw": {
            "geenRechtMeerWw": "NEE",
            "geenRechtMeerWga": "NEE",
            "gedeeltelijkArbeidsongeschikt": "NEE"
          }
        },
        "schulden": {
          "heeftSchulden": "NEE"
        },
        "alo-uitbetaling": {
          "ibanAanWie": "NEE"
        },
        "alo-uw-inkomsten": {
          "heeftInkomsten": "GEEN_INKOMSTEN"
        },
        "alo-reden-aanvraag": {
          "grDetentie": {
            "hoeLangDetentie": "31_DAGEN_OF_LANGER",
            "laatsteDagDetentie": "2025-09-09",
            "uitkeringGehadDetentie": "JA",
            "welkeUitkeringDetentie": "BIJSTAND"
          },
          "grIngangsdatum": {
            "bijstandsuitkeringEerderStarten": "JA",
            "welkeredenlaat": "WACHTEN_BESLISSING_INSTANTIE",
            "welkeBeslissing": "Vrijlating gevangenis",
            "wanneerBeslissing": "2025-07-02"
          },
          "waaromBijstandsuitkering": "DETENTIE"
        },
        "alo-uw-woonsituatie": {
          "grHuur": {
            "hoeveelHuur": 78,
            "huurcontract": "JA",
            "wieVerhuurder": "Wiebren Haga",
            "contractOpUwNaam": "JA",
            "hoeveelHuurtoeslag": 12
          },
          "hoeWoontU": "ZELFSTANDIGE_HUURWONING",
          "grAndereBewoners": {
            "meerMensenOpAdres": "NEE"
          }
        },
        "alo-uw-beschikbaarheid": {
          "grBeschikbaarheid": {
            "onbetaald": "NEE",
            "beschikbaarheid": 2
          }
        },
        "alo-gezinssamenstelling": {
          "partnerWoontBijU": "NEE",
          "thuiswonendeKinderen": "NEE"
        },
        "alo-aanvullende-gegevens": {
          "lieverPost": false,
          "grWoonsituatie": {
            "woonsituatie": "WAAR_IK_WOON"
          },
          "grNationaliteit": {
            "nationaliteitBezit": "NEDERLANDSE_NATIONALITEIT"
          },
          "grContactAanvraag": {
            "hulpAanvraag": "NEE"
          },
          "grNieuweContactgegevens": {
            "geenEmail": false,
            "emailAdres": "jouw.naam@ritense.com",
            "geenTelefoon": true
          }
        },
        "alo-bezittingen-en-schulden": {
          "grRekeningen": {
            "geenBankrekening": "GEEN_REKENING"
          },
          "grUwVermogen": {
            "welkVermogen": {
              "CRYPTO": false,
              "CARAVAN": false,
              "VAARTUIG": false,
              "CONTANTEN": false,
              "KOOPWONING": false,
              "MOTORVOERTUIG": false,
              "EEN_STUK_GROND": false,
              "OBLIGATIES_AANDELEN": false
            }
          }
        }
      },
      "type": "Verzoek AB DCM",
      "language_code": "nl",
      "submission_id": "984d8f41-44fb-4759-a90a-4763531bc713",
      "public_reference": "OF-{{$random.alphanumeric(8)}}"
    },
    "startAt": "2025-07-08",
    "registrationAt": "2025-07-08"
  }
}
