POST {{objects_api_url}}
Authorization: Token {{token}}
Content-Crs: EPSG:4326
Content-Type: application/json

{
  "type": "{{objecttypes_api_url_alo}}",
  "record": {
    "index": 1,
    "typeVersion": "{{objecttypes_version}}",
    "data": {
      "bsn": "999991322",
      "data": {
        "your-details": {
          "naw": {
            "grAdresgegevens": {
              "plaats": "'s-Gravenhage",
              "straat": "Herengracht",
              "postcode": "2511 EG",
              "huisletter": "",
              "huisnummer": "1",
              "toevoeging": ""
            },
            "grPersoongegevens": {
              "Bsn": "999991322",
              "voornaam": "Celeste",
              "achternaam": "Avion",
              "voorletters": "C.",
              "voorvoegsels": "",
              "geboortedatum": "1960-12-29"
            }
          }
        },
        "alo-ioaw": {
          "grIoaw": {
            "geenRechtMeerWw": "NEE",
            "geenRechtMeerWga": "NEE",
            "gedeeltelijkArbeidsongeschikt": "NEE"
          }
        },
        "schulden": {
          "heeftSchulden": "NEE"
        },
        "alo-uitbetaling": {
          "ibanAanWie": "NEE",
          "ibanUitbetaling": "NL24HSBC0509175090",
          "naamRekeninghouder": "w"
        },
        "alo-uw-inkomsten": {
          "heeftInkomsten": "GEEN_INKOMSTEN"
        },
        "alo-reden-aanvraag": {
          "grIngangsdatum": {
            "bijstandsuitkeringEerderStarten": "NEE"
          },
          "grVerblijfstatus": {
            "stoptWeekgeld": "NEE",
            "hoeveelWeekgeld": 500,
            "ontvangtWeekgeld": "JA",
            "redenVerblijfstatus": "VERBLIJFSDOCUMENT"
          },
          "waaromBijstandsuitkering": "VERBLIJFSTATUS"
        },
        "alo-uw-woonsituatie": {
          "grHuur": {
            "hoeveelHuur": 8000,
            "huurcontract": "JA",
            "wieVerhuurder": "Misty Erie",
            "contractOpUwNaam": "JA",
            "hoeveelHuurtoeslag": 100
          },
          "hoeWoontU": "ZELFSTANDIGE_HUURWONING",
          "grAndereBewoners": {
            "meerMensenOpAdres": "NEE"
          }
        },
        "alo-uw-beschikbaarheid": {
          "grBeschikbaarheid": {
            "onbetaald": "NEE",
            "beschikbaarheid": 5
          }
        },
        "alo-gezinssamenstelling": {
          "partnerWoontBijU": "NEE",
          "thuiswonendeKinderen": "NEE"
        },
        "alo-aanvullende-gegevens": {
          "lieverPost": true,
          "grWoonsituatie": {
            "woonsituatie": "WAAR_IK_WOON"
          },
          "grNationaliteit": {
            "nationaliteitBezit": "NEDERLANDSE_NATIONALITEIT"
          },
          "grContactAanvraag": {
            "hulpAanvraag": "NEE"
          },
          "grNieuweContactgegevens": {
            "geenEmail": false,
            "emailAdres": "jouw.naam@ritense.com",
            "geenTelefoon": true
          }
        },
        "alo-bezittingen-en-schulden": {
          "grRekeningen": {
            "grLogicaBank": {
              "hhgVoegRekeningToe": [
                {
                  "zakelijk": "NL24HSBC0509175090",
                  "hoeveelGeld": 14,
                  "typeRekening": "NEDERLANDSE_ZAKELIJKE_REKENING",
                  "uploadAfschrift": []
                }
              ]
            },
            "geenBankrekening": "BEZIT_REKENING"
          },
          "grUwVermogen": {
            "welkVermogen": {
              "CRYPTO": false,
              "CARAVAN": false,
              "VAARTUIG": false,
              "CONTANTEN": false,
              "KOOPWONING": false,
              "MOTORVOERTUIG": false,
              "EEN_STUK_GROND": false,
              "OBLIGATIES_AANDELEN": false
            }
          }
        }
      },
      "type": "Verzoek AB DCM",
      "language_code": "nl",
      "submission_id": "87e7297b-06df-4e19-920e-7a596b99a661",
      "public_reference": "OF-{{$random.alphanumeric(8)}}"
    },
    "startAt": "2025-07-08",
    "registrationAt": "2025-07-08"
  }
}