POST {{objects_api_url}}
Authorization: Token {{token}}
Content-Crs: EPSG:4326
Content-Type: application/json


{
    "type": "{{objecttypes_api_url}}",
    "record": {
        "index": 1,
        "typeVersion": 1,
        "data": {
            "bsn": "111111110",
            "data": {
                "uw-gegevens": {
                    "digid": {
                        "persoongegevensPrefill": {
                            "BsnPrefill": "111111110",
                            "voornaamPrefill": "Sierra",
                            "achternaamPrefill": "Kooyman",
                            "voorlettersPrefill": "S.",
                            "voorvoegselPrefill": "",
                            "geboortedatumPrefill": "2003-03-03"
                        },
                        "adresgegevensPrefillGroep": {
                            "plaatsPrefill": "'s-Gravenhage",
                            "straatPrefill": "Leyweg",
                            "postcodePrefill": "2545 CC",
                            "HuisletterPrefill": "e",
                            "huisnummerPrefill": 61,
                            "toevoegingPrefill": ""
                        }
                    },
                    "contactgegevens": {
                        "email": "laurens1@denhaag.nl",
                        "Telefoonnummer": "0612345678"
                    }
                },
                "foo-aanvullende-gegevens": {
                    "woonsituatieGr": {
                        "woonsituatie": "IK_STA_INGESCHREVEN_BIJ_DE_GEMEENTE_OP_HET_ADRES_WAAR_IK_WOON"
                    },
                    "verblijfAdresGr": {
                        "straatVerblijf": "Grote Brekkenstraat",
                        "postcodeVerblijf": "1234FG",
                        "huisletterVerblijf": "L",
                        "huisnummerVerblijf": 12,
                        "woonplaatsVerblijf": "Bussum",
                        "toelichtingVerblijf": "Toelichting verblijf adres",
                        "huisnummerToevoeging": "1e verdieping"
                    },
                    "nationaliteitGR": {
                        "watGedaanBehouden": "VERLENGING_VAN_MIJN_VERBLIJFSDOCUMENT_AANGEVRAAGD",
                        "nationaliteitBezit": "MIJN_VERBLIJFSVERGUNNING_IS_VERLOPEN"
                    },
                    "contactAanvraagGr": {
                        "contactHulpGr": {
                            "naamHulp": "henk",
                            "relatieHulp": "FAMILIE",
                            "telefoonHulp": "1234567890"
                        },
                        "hulpBijAanvraag": "JA"
                    },
                    "jaIkWilPostOntvangen": true
                },
                "foo-uitbetaling": {
                    "ibanUitbetaling": "NL80ABNA0369127188",
                    "hoeBetaaldKrijgen": "VOLLEDIG_OP_MIJN_REKENING",
                    "uitkeringAanDerden": "NEE",
                    "naamRekeninghouderBetaling": "Erik"
                },
                "foo-uw-ondernemingen": {
                    "ondernemingGr": {
                        "ingeschrevenKvk": "JA"
                    },
                    "10JaarOnafgebroken": "NEE",
                    "ingeschrevenOnderneming": [
                        {
                            "kvk": "69599084",
                            "ondernemingNaam": "Erik",
                            "inschrijvingsDatum": "2000-11-11",
                            "korteOmschrijving": "Test aanvraag Erik",
                            "rechtsvorm": "EENMANSZAAK_ZZP",
                            "aantalVernoten": 42,
                            "eindBaas": "NEE",
                            "bezitDiplomas": "NVT",
                            "aanvraagFaillissement": "NEE",
                            "aanvraagSurseance": "NEE",
                            "stoppenOnderneming": "NEE",
                            "werkzaamhedenOfLopendeVerplichtingen": "NEE",
                            "stoppenVerklaring": "Ik ga met pensioen"
                        }
                    ]
                },
                "foo-uw-aanvraag": {
                    "uwAanvraag": {
                        "WAT_IK_WIL_AANVRAGEN_STAAT_HIER_NIET_TUSSEN": false,
                        "EEN_BBZ_UITKERING_OMDAT_U_WILT_STOPPEN_MET_ONDERNEMEN": true,
                        "EEN_BBZ_UITKERING_VOOR_STARTENDE_ONDERNEMERS_OF_ONDERNEMERS_DIE_KORTER_DAN_1_5_JAAR_ONDERNEMEN": false,
                        "EEN_BBZ_UITKERING_VOOR_ONDERNEMERS_DIE_LANGER_DAN_1_5_JAAR_ONDERNEMEN": false,
                        "EEN_BBZ_UITKERING_VOOR_OUDERE_ONDERNEMERS_DIE_VOOR_1_JANUARI_1960_ZIJN_GEBOREN": false,
                        "EEN_IOAZ_UITKERING_OMDAT_U_WILT_STOPPEN_MET_ONDERNEMEN_EN_OUDER_BENT_DAN_55_JAAR": true,
                        "EEN_BEDRIJFSKREDIET": true
                    }
                },
                "foo-gezinssamenstelling": {
                    "gegevensPartner": {
                        "bsnPartner": "111111110",
                        "Adresgegevensp": {
                            "plaatsp": "Bussum",
                            "straatp": "Wielstraat",
                            "postcodep": "1234 ab",
                            "Huisletterp": "g",
                            "huisnummerp": 2,
                            "toevoegingHuisnummerPartner": "de"
                        },
                        "geboortePartner": "2024-03-19",
                        "achternaamParnter": "Meer",
                        "voorletterPartner": "B",
                        "voorvoegsePartner": "van",
                        "partnerVerblijf": "MIJN_PARTNER_HEEFT_VERLENGING_VAN_HET_VERBLIJFSDOCUMENT_AANGEVRAAGD",
                        "partnerZelfdeAdres": "NEE_MIJN_PARTNER_WOONT_OP_EEN_ANDER_ADRES",
                        "nationaliteitPartner": "MIJN_PARTNER_IS_EEN_EU_ONDERDAAN"
                    },
                    "gezinssituatieGr": {
                        "partnerDieBijUWoont": "JA",
                        "thuiswonendeKinderen": "JA"
                    },
                    "nationaliteitPartnerGr": {
                        "uOfUwPartnerHeeftNietDeNederlandseNationaliteit": "JA"
                    },
                    "gegevensVanUwKinderengroep": {
                        "gegevensVanUwKinderen": [
                            {
                                "achternaamk": "Bakker",
                                "veldengroepk": {
                                    "welkSoortOpleidingVolgtUwKind": "MIJN_KIND_ZIT_OP_DE_BASISSCHOOL_MIDDELBARE_SCHOOL_OF_VOLGT_GEEN_OPLEIDING",
                                    "krijgtUKinderbijslagVoorDitKind": "NEE"
                                },
                                "voorletterSk": "BA",
                                "voorvoegselSk": "",
                                "geboortedatumk": "2024-03-01",
                                "burgerservicenummerk": "444444440",
                                "voornamenZoalsOpPaspoortIdStaan": "Bart Andreas"
                            }
                        ]
                    }
                },
                "foo-bezittingen-en-schulden": {
                    "heeftSchulden": "JA",
                    "schuldenGroep": {
                        "schuldHerGroep": [
                            {
                                "schuldBedrag": 1111,
                                "schuldBijWie": "Erik"
                            }
                        ]
                    },
                    "rekeningenGroep": {
                        "rekeningHerGroep": [
                            {
                                "ibanPrive": "NL80ABNA0369127188",
                                "saldoRekening": 1212,
                                "welkeRekeningen": "NEDERLANDSE_PRIVE_REKENING",
                                "uploadSaldoRekening": [
                                ]
                            }
                        ]
                    },
                    "uwVermogenGroep": {
                        "welkVermogen": {
                            "CRYPTO": false,
                            "CARAVAN": false,
                            "VAARTUIG": false,
                            "CONTANTEN": false,
                            "OBLIGATIES_AANDELEN": false,
                            "EEN_MOTORVOERTUIG_AUTO_CAMPER_OF_MOTOR": false,
                            "EEN_STUK_GROND_IN_NEDERLAND_EN_OF_HET_BUITENLAND": false,
                            "BANK_EN_SPAARREKENINGEN_PRIVE_EN_ZAKELIJK_BINNEN_EN_BUITENLAND": true,
                            "EEN_OF_MEERDERE_KOOPWONING_EN_IN_NEDERLAND_EN_OF_HET_BUITENLAND": false
                        }
                    }
                },
                "foo-uw-inkomsten": {
                    "vormenInkomsten": {
                        "PENSIOEN": false,
                        "UITKERING": false,
                        "LOONDIENST": true,
                        "ALIMENTATIE": true,
                        "HEFFINGSKORTING": false,
                        "OVERIGE_INKOMSTEN": false,
                        "IK_HEB_GEEN_INKOMSTEN": false,
                        "INKOMSTEN_UIT_ONDERHUUR": false,
                        "INKOMEN_UIT_HET_BUITENLAND": false
                    },
                    "alimentatieGroep": {
                        "krijgtHulp": "NEE",
                        "KrijgtRecht": "NEE",
                        "alimentatieKind": "JA",
                        "lbioIngeschakeld": "JA",
                        "hoeveelAlimentatieKind": 121
                    },
                    "loondienstWerkgeverS": {
                        "werkgeversHerGroep": [
                            {
                                "nettoloon": 600,
                                "loonstroken": [
                                ],
                                "aantalUurWerk": 12,
                                "naamWerkgever": "Erik BV",
                                "soortContract": "IK_HEB_EEN_UITZENDCONTRACT",
                                "periodeNettoloon": "PER_4_WEKEN",
                                "urenvermindering": "NEE",
                                "contractBeeindigd": "NEE",
                                "Loonheffingskorting": "NEE",
                                "uitbetalingNaastLoon": {
                                    "GEEN": false,
                                    "LOON_IN_NATURA": false,
                                    "MAALTIJDVERGOEDING": false,
                                    "ONKOSTENVERGOEDING": false,
                                    "REISKOSTENVERGOEDING": false,
                                    "1_KEER_PER_JAAR_VAKANTIEGELD": true,
                                    "EEN_13DE_MAAND_OF_EINDEJAARSUITKERING": false,
                                    "VAKANTIEGELD_BIJ_IEDERE_UITBETALING_VAN_MIJN_SALARIS": false
                                }
                            }
                        ]
                    }
                },
                "foo-financiele-situatie": {
                    "bedrijfspandGroep": {
                        "typeBedrijfspand": "IK_HUUR_MIJN_BEDRIJFSPAND"
                    },
                    "inkomenOndernemingGroep": {
                        "waaromHulp": "Eten en huur",
                        "welkeMaandenHulp": "komende 3",
                        "winstKomendeMaanden": 0
                    },
                    "situatieOndernemingGroep": {
                        "voldoendeInkomsten": "JA",
                        "resultaatHuidigJaar": "IK_HEB_IN_HET_HUIDIGE_BOEKJAAR_GEEN_ONDERNEMING",
                        "toestemmingOnderzoek": "JA",
                        "finSituatieOnderneming": [
                            {
                                "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/c9d0f755-8e04-414a-b32e-d7dafa597e70",
                                "data": {
                                    "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/c9d0f755-8e04-414a-b32e-d7dafa597e70",
                                    "form": "",
                                    "name": "Screenshot 2024-02-15 at 11.10.27.png",
                                    "size": 3845,
                                    "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                    "project": ""
                                },
                                "name": "Screenshot 2024-02-15 at 11.10.27-549eed05-2bd3-4dea-ab22-7b935da51f94.png",
                                "size": 3845,
                                "type": "image/png",
                                "storage": "url",
                                "originalName": "Screenshot 2024-02-15 at 11.10.27.png"
                            }
                        ],
                        "resultaatEenJaarGeleden": 11,
                        "resultaatDrieJaarGeleden": 111,
                        "resultaatTweeJaarGeleden": 11,
                        "aangifteBelastingAanleveren": "JA",
                        "resultaatEenJaarBeschikbaar": "JA",
                        "resultaatDrieJaarBeschikbaar": "JA",
                        "resultaatTweeJaarBeschikbaar": "JA"
                    }
                },
                "foo-uw-woonsituatie": {
                    "hoeWonen": "IK_HUUR_EEN_KAMER_EN_HEB_HIERVAN_EEN_HUURCONTRACT",
                    "andereBewonersGroep": {
                        "meerOpAdres": "JA",
                        "andereBewonersGroep1": {
                            "medebewonerHGroep": [
                                {
                                    "samenEten": {
                                        "WIJ_ETEN_SAMEN": true,
                                        "WIJ_GAAN_SAMEN_OP_VAKANTIE": false,
                                        "WIJ_VERDELEN_OF_DOEN_SAMEN_DE_TAKEN_IN_HET_HUISHOUDEN": true,
                                        "WIJ_ETEN_NIET_SAMEN_GAAN_NIET_SAMEN_OP_VAKANTIE_EN_VERDELEN_GEEN_TAKEN_IN_HET_HUISHOUDEN": false
                                    },
                                    "soortOpleiding": "HBO",
                                    "kostenVerdeling": {
                                        "WIJ_DELEN_DE_KOSTEN_VAN_DE_HUUR": true,
                                        "WIJ_DELEN_DE_KOSTEN_VAN_DE_BOODSCHAPPEN": false,
                                        "WIJ_DELEN_DE_VASTE_LASTEN_ZOALS_GAS_EN_WATER": true,
                                        "WIJ_DELEN_NIET_DE_KOSTEN_VAN_DE_HUUR_DE_VASTE_LASTEN_ZOALS_GAS_EN_WATER_OF_DE_KOSTEN_VAN_DE_BOODSCHAPPEN": false
                                    },
                                    "relatieMedebewoner": "IEMAND_DIE_EEN_KAMER_BIJ_MIJ_HUURT",
                                    "huishoudingSituatie": {
                                        "WIJ_HEBBEN_EEN_SAMENLEVINGSCONTRACT": true,
                                        "WIJ_HEBBEN_SAMEN_EEN_KIND_OF_EEN_ERKEND_KIND": false,
                                        "WIJ_ZIJN_IN_DE_AFGELOPEN_2_JAAR_GEHUWD_OF_GEREGISTREERD_PARTNER_GEWEEST": false,
                                        "WIJ_WORDEN_OF_WERDEN_IN_DE_AFGELOPEN_2_JAAR_ALS_1_HUISHOUDEN_GEZIEN_DOOR_EEN_OVERHEIDSINSTANTIE": false,
                                        "WIJ_ZIJN_IN_DE_AFGELOPEN_2_JAAR_NIET_GEHUWD_OF_GEREGISTREERD_PARTNER_GEWEEST_WIJ_HEBBEN_SAMEN_GEEN_ERKEND_KIND_WIJ_HEBBEN_GEEN_SAMENLEVINGSCONTRACT_WIJ_WORDEN_OF_WERDEN_IN_DE_AFGELOPEN_2_JAAR_NIET_GEZIEN_ALS_1_HUISHOUDEN_DOOR_EEN_OVERHEIDSINSTANTIE": false
                                    },
                                    "medebewonerOpleiding": "JA",
                                    "achternaamMedebewoner": "medebewoner",
                                    "voorlettersMedebewoner": "b",
                                    "voorvoegselMedebewoner": "b",
                                    "bsnMedebewoner2": "222222220",
                                    "geboortedatumMedebewoner": "1990-03-01",
                                    "grOntvangenHuur": {
                                        "ontvangenHuur": 1250,
                                        "periodeHuur": "MAAND"
                                    }
                                }
                            ]
                        }
                    },
                    "huurGroep": {
                        "huurcontract": "JA",
                        "vanWieKamer": "Huurbedrijf A",
                        "wieVerhuurder": "Huurbedrijf B",
                        "contractOpUwNaam": "JA",
                        "welkeNaamHuurcontract": "Kooyman",
                        "hoeveelHuur": 1250,
                        "hoeveelHuurtoeslag": 950,
                        "bijOudersInwonen": "JA",
                        "waaromNietBijOudersWonen": "Geen kamer beschikbaar"
                    },
                    "bijWieWoontU": "BIJ_MIJN_OUDER_S",
                    "wonenRelatie": "Omschrijving wonen relatie",
                    "zorgInstellingGroep": {
                        "wonenZorginstelling": "Zorginstelling de hoop",
                        "postcodeZorginstelling": "1234AB",
                        "huisnummerZorginstelling": 3,
                        "straatnaamZorginstelling": "Waterstraat"
                    },
                    "maatschappelijkeOpvangGroep": {
                        "WelkeOpvang": "Opvang de hoop",
                        "postcodeOpvang": "1234AB",
                        "huisnummerOpvang": 151,
                        "straatnaamMaatschappelijkeOpvang": "Maatschappelijke opvang straat",
                        "dagenOpvang": 453
                    }
                },
                "foo-bedrijfskrediet": {
                    "andereLeningen": "NEE",
                    "isBeslaglegging": "NEE",
                    "contactSchuldhulp": "NEE",
                    "redenBedrijfskrediet": {
                        "SANERING": false,
                        "ACHTERSTANDEN": true,
                        "INVESTERINGEN": true,
                        "ANDERS_NAMELIJK": false,
                        "HERFINANCIERING": false
                    },
                    "bedragBedrijfskrediet": 10000,
                    "toelichtingBedrijfskrediet": "Nieuwe machine"
                }
            },
            "type": "verzoek-bbz-aanvraag",
            "attachments": [],
            "language_code": "nl",
            "submission_id": "9e036264-7cee-41ba-b8b5-ea433fb22092"
        },
        "geometry": null,
        "startAt": "2024-03-19",
        "endAt": null,
        "registrationAt": "2024-03-19"
    }
}

###

