POST {{objects_api_url}}
Authorization: Token {{token}}
Content-Crs: EPSG:4326
Content-Type: application/json


{
    "type": "{{objecttypes_api_url}}",
    "record": {
        "data": {
            "bsn": "999991954",
            "data": {
                "uw-gegevens": {
                    "digid": {
                        "persoongegevensPrefill": {
                            "BsnPrefill": "999991954",
                            "voornaamPrefill": "Sierra",
                            "achternaamPrefill": "Kooyman",
                            "voorlettersPrefill": "S.",
                            "voorvoegselPrefill": "",
                            "geboortedatumPrefill": "2003-03-03"
                        },
                        "adresgegevensPrefillGroep": {
                            "plaatsPrefill": "'s-Gravenhage",
                            "straatPrefill": "Leyweg",
                            "postcodePrefill": "2545 CC",
                            "HuisletterPrefill": "e",
                            "huisnummerPrefill": 61,
                            "toevoegingPrefill": ""
                        }
                    },
                    "contactgegevens": {
                        "email": "erik.de.vries@ritense.com",
                        "Telefoonnummer": "0612345678"
                    }
                },
                "foo-inleiding": {},
                "foo-uitbetaling": {
                    "uitbetalingGroep": {
                        "ibanDerden": "NL20RBOS0000345571",
                        "waaromAanDerden": "Dit is een test voor reden uitkering",
                        "naamDerdenRekeninghouder": "Test Naam",
                        "adresDerdenRekeninghouder": "Rotterdam"
                    },
                    "uitkeringAanDerden": "JA"
                },
                "foo-uw-aanvraag": {
                    "uwAanvraag": {
                        "WAT_IK_WIL_AANVRAGEN_STAAT_HIER_NIET_TUSSEN": false,
                        "EEN_BBZ_UITKERING_OMDAT_U_WILT_STOPPEN_MET_ONDERNEMEN": false,
                        "EEN_BBZ_UITKERING_VOOR_ONDERNEMERS_DIE_LANGER_DAN_1_5_JAAR_ONDERNEMEN": true
                    }
                },
                "foo-uw-inkomsten": {
                    "vormenInkomsten": {
                        "PENSIOEN": false,
                        "UITKERING": false,
                        "LOONDIENST": false,
                        "ALIMENTATIE": false,
                        "HEFFINGSKORTING": false,
                        "OVERIGE_INKOMSTEN": true,
                        "IK_HEB_GEEN_INKOMSTEN": false,
                        "INKOMSTEN_UIT_ONDERHUUR": false,
                        "INKOMEN_UIT_HET_BUITENLAND": false
                    },
                    "overigeInkomsten": {
                        "overigbedrag": 120
                    }
                },
                "foo-uw-woonsituatie": {
                    "hoeWonen": "IK_WOON_IN_MIJN_EIGEN_KOOPWONING_OF_WOONBOOT",
                    "andereBewonersGroep": {
                        "meerOpAdres": "NEE"
                    }
                },
                "foo-uw-ondernemingen": {
                    "ondernemingGr": {
                        "ingeschrevenKvk": "JA"
                    },
                    "ingeschrevenOnderneming": [
                        {
                            "kvk": "69599084",
                            "eindBaas": "JA",
                            "rechtsvorm": "BESLOTEN_VENNOOTSCHAP_BV",
                            "bezitDiplomas": "JA",
                            "ondernemingNaam": "Test Onderneming",
                            "aanvraagSurseance": "JA",
                            "korteOmschrijving": "Test omschrijving",
                            "stoppenVerklaring": "Dit is een korte omschrijving waarom ik wil stoppen",
                            "inschrijvingsDatum": "2010-11-11",
                            "stoppenOnderneming": "JA",
                            "aanvraagFaillissement": "JA",
                            "verklaringOndernemingd": [
                                {
                                    "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/64ec2a4a-b673-44ab-b268-e2f3e1d28d32",
                                    "data": {
                                        "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/64ec2a4a-b673-44ab-b268-e2f3e1d28d32",
                                        "form": "",
                                        "name": "Screenshot 2024-04-23 at 11.41.50.png",
                                        "size": 4930,
                                        "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                        "project": ""
                                    },
                                    "name": "Screenshot 2024-04-23 at 11.41.50-8149abb5-5205-41f4-b62f-54e842cf0593.png",
                                    "size": 4930,
                                    "type": "image/png",
                                    "storage": "url",
                                    "originalName": "Screenshot 2024-04-23 at 11.41.50.png"
                                }
                            ],
                            "werkzaamhedenOfLopendeVerplichtingen": "JA"
                        }
                    ]
                },
                "foo-inkomsten-partner": {
                    "vormenInkomstenPartner": {
                        "PENSIOEN": false,
                        "UITKERING": true,
                        "LOONDIENST": false,
                        "ALIMENTATIE": false,
                        "HEFFINGSKORTING": false,
                        "OVERIGE_INKOMSTEN": false,
                        "INKOMSTEN_UIT_ONDERHUUR": false,
                        "INKOMSTEN_UIT_ONDERNEMING": false,
                        "INKOMEN_UIT_HET_BUITENLAND": false,
                        "MIJN_PARTNER_HEEFT_GEEN_INKOMEN": false
                    },
                    "uitkeringenPartnerGroep": {
                        "wwPartnerGroep": {
                            "nettoWwPartner": 1100,
                            "periodeWwPartner": "MAAND",
                            "overzichtWwPartner": [
                                {
                                    "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/5fec479f-b728-44e7-93a0-d9bb7796911c",
                                    "data": {
                                        "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/5fec479f-b728-44e7-93a0-d9bb7796911c",
                                        "form": "",
                                        "name": "Screenshot 2024-04-23 at 12.08.22.png",
                                        "size": 5065,
                                        "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                        "project": ""
                                    },
                                    "name": "Screenshot 2024-04-23 at 12.08.22-e214fd8a-2d51-4a52-8832-e2e21e3a95bb.png",
                                    "size": 5065,
                                    "type": "image/png",
                                    "storage": "url",
                                    "originalName": "Screenshot 2024-04-23 at 12.08.22.png"
                                }
                            ]
                        },
                        "uitkeringenPartner": {
                            "WW": true,
                            "ANW": false,
                            "AOW": false,
                            "WAO": false,
                            "WIA": false,
                            "GEEN": false,
                            "WAJONG": false,
                            "BIJSTAND": false,
                            "ZIEKTEWET": false
                        }
                    }
                },
                "foo-financiele-situatie": {
                    "bedrijfspandGroep": {
                        "typeBedrijfspand": "IK_HUUR_MIJN_BEDRIJFSPAND",
                        "uploadContractBedrijfspand": [
                            {
                                "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/d4f2dc1f-b637-41a4-b646-a7a547dbdfb3",
                                "data": {
                                    "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/d4f2dc1f-b637-41a4-b646-a7a547dbdfb3",
                                    "form": "",
                                    "name": "Screenshot 2024-04-23 at 12.03.35.png",
                                    "size": 5066,
                                    "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                    "project": ""
                                },
                                "name": "Screenshot 2024-04-23 at 12.03.35-4bc9fa35-666d-42ef-a210-c58734021a85.png",
                                "size": 5066,
                                "type": "image/png",
                                "storage": "url",
                                "originalName": "Screenshot 2024-04-23 at 12.03.35.png"
                            }
                        ]
                    },
                    "inkomenOndernemingGroep": {
                        "waaromHulp": "Dit is een test",
                        "welkeMaandenHulp": "april",
                        "winstKomendeMaanden": 0
                    },
                    "situatieOndernemingGroep": {
                        "voldoendeInkomsten": "NEE",
                        "resultaatHuidigJaar": "JA",
                        "toestemmingOnderzoek": "JA",
                        "finSituatieOnderneming": [
                            {
                                "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/d4990268-5bcd-432d-a158-181a2839b526",
                                "data": {
                                    "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/d4990268-5bcd-432d-a158-181a2839b526",
                                    "form": "",
                                    "name": "Screenshot 2024-04-23 at 12.02.56.png",
                                    "size": 4504,
                                    "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                    "project": ""
                                },
                                "name": "Screenshot 2024-04-23 at 12.02.56-59b99d26-4b50-4777-8ed5-dc7c77270d00.png",
                                "size": 4504,
                                "type": "image/png",
                                "storage": "url",
                                "originalName": "Screenshot 2024-04-23 at 12.02.56.png"
                            }
                        ],
                        "resultaatEenJaarGeleden": -10000,
                        "resultaatDrieJaarGeleden": 10000,
                        "resultaatTweeJaarGeleden": -2000,
                        "resultaatHuidigJaarBedrag": -5000,
                        "aangifteBelastingAanleveren": "JA",
                        "resultaatEenJaarBeschikbaar": "JA",
                        "resultaatDrieJaarBeschikbaar": "JA",
                        "resultaatTweeJaarBeschikbaar": "JA"
                    }
                },
                "foo-gezinssamenstelling": {
                    "gegevensPartner": {
                        "bsnPartner": "080000071",
                        "geboortePartner": "1991-02-25",
                        "uploadIdPartner": [
                            {
                                "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/dac074dc-7ed5-4756-bf50-0c383e9df759",
                                "data": {
                                    "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/dac074dc-7ed5-4756-bf50-0c383e9df759",
                                    "form": "",
                                    "name": "Screenshot 2024-04-23 at 11.54.32.png",
                                    "size": 4967,
                                    "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                    "project": ""
                                },
                                "name": "Screenshot 2024-04-23 at 11.54.32-519def16-db39-4de3-b1bc-563590f2cf9a.png",
                                "size": 4967,
                                "type": "image/png",
                                "storage": "url",
                                "originalName": "Screenshot 2024-04-23 at 11.54.32.png"
                            }
                        ],
                        "achternaamParnter": "Jansen",
                        "voorletterPartner": "TP",
                        "voorvoegsePartner": "",
                        "partnerZelfdeAdres": "JA",
                        "nationaliteitPartner": "MIJN_PARTNER_HEEFT_DE_NEDERLANDSE_NATIONALITEIT"
                    },
                    "gezinssituatieGr": {
                        "partnerDieBijUWoont": "JA",
                        "thuiswonendeKinderen": "JA"
                    },
                    "gegevensVanUwKinderengroep": {
                        "gegevensVanUwKinderen": [
                            {
                                "achternaamk": "Jansen",
                                "veldengroepk": {
                                    "welkSoortOpleidingVolgtUwKind": "MIJN_KIND_ZIT_OP_DE_BASISSCHOOL_MIDDELBARE_SCHOOL_OF_VOLGT_GEEN_OPLEIDING",
                                    "krijgtUKinderbijslagVoorDitKind": "JA"
                                },
                                "voorletterSk": "LVM",
                                "voorvoegselSk": "",
                                "geboortedatumk": "2017-08-19",
                                "burgerservicenummerk": "010002546",
                                "voornamenZoalsOpPaspoortIdStaan": "Lev Vigo Mels"
                            }
                        ]
                    }
                },
                "foo-waarheidsverklaring": {
                    "ikVulDitFormulierNaarWaarheidIn": true
                },
                "foo-aanvullende-gegevens": {
                    "woonsituatieGr": {
                        "woonsituatie": "IK_ZIT_IN_ELEKTRONISCHE_DETENTIE"
                    },
                    "nationaliteitGR": {
                        "nationaliteitBezit": "IK_HEB_DE_NEDERLANDSE_NATIONALITEIT"
                    },
                    "verblijfAdresGr": {
                        "straatVerblijf": "Spui",
                        "postcodeVerblijf": "2511 BT",
                        "huisletterVerblijf": "",
                        "huisnummerVerblijf": 70,
                        "woonplaatsVerblijf": "'s-Gravenhage",
                        "toelichtingVerblijf": "Test omschrijving",
                        "huisnummerToevoeging": ""
                    },
                    "contactAanvraagGr": {
                        "contactHulpGr": {
                            "naamHulp": "Contact Test",
                            "relatieHulp": "BOEKHOUDER",
                            "telefoonHulp": "0612345678"
                        },
                        "hulpBijAanvraag": "JA"
                    },
                    "jaIkWilPostOntvangen": false
                },
                "foo-uw-inkomsten-overzicht": {},
                "foo-bezittingen-en-schulden": {
                    "heeftSchulden": "NEE",
                    "koopwoningGroep": {
                        "wozWoning": 220000,
                        "resterendeHypotheek": 230000,
                        "productenAanHypotheek": "JA",
                        "uploadHypotheekschuld": [
                            {
                                "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/a729036c-db99-4db8-892d-590ebd52e513",
                                "data": {
                                    "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/a729036c-db99-4db8-892d-590ebd52e513",
                                    "form": "",
                                    "name": "Screenshot 2024-04-23 at 12.12.14.png",
                                    "size": 4938,
                                    "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                    "project": ""
                                },
                                "name": "Screenshot 2024-04-23 at 12.12.14-b6c949ec-4d82-445a-9a11-eef1a2d4425c.png",
                                "size": 4938,
                                "type": "image/png",
                                "storage": "url",
                                "originalName": "Screenshot 2024-04-23 at 12.12.14.png"
                            }
                        ]
                    },
                    "rekeningenGroep": {
                        "rekeningHerGroep": [
                            {
                                "ibanPrive": "NL51BOFS0595324851",
                                "saldoRekening": -300,
                                "welkeRekeningen": "NEDERLANDSE_PRIVE_REKENING",
                                "uploadSaldoRekening": [
                                    {
                                        "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/f5a19e78-e90a-4ebf-9602-54b9519e7b1b",
                                        "data": {
                                            "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/f5a19e78-e90a-4ebf-9602-54b9519e7b1b",
                                            "form": "",
                                            "name": "Screenshot 2024-04-23 at 12.10.54.png",
                                            "size": 4659,
                                            "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                            "project": ""
                                        },
                                        "name": "Screenshot 2024-04-23 at 12.10.54-115cd093-83a5-489d-83bf-ae2342854375.png",
                                        "size": 4659,
                                        "type": "image/png",
                                        "storage": "url",
                                        "originalName": "Screenshot 2024-04-23 at 12.10.54.png"
                                    }
                                ]
                            },
                            {
                                "ibanZakelijk": "NL04HAND0554116243",
                                "saldoRekening": -1200,
                                "welkeRekeningen": "NEDERLANDSE_ZAKELIJKE_REKENING",
                                "uploadSaldoRekening": [
                                    {
                                        "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/70719cab-3807-4d95-bb51-b4705b653f72",
                                        "data": {
                                            "url": "https://openformulieren-zgw.test.denhaag.nl/api/v2/submissions/files/70719cab-3807-4d95-bb51-b4705b653f72",
                                            "form": "",
                                            "name": "Screenshot 2024-04-23 at 12.11.37.png",
                                            "size": 5060,
                                            "baseUrl": "https://openformulieren-zgw.test.denhaag.nl/api/v2/",
                                            "project": ""
                                        },
                                        "name": "Screenshot 2024-04-23 at 12.11.37-9d7cbcc4-3c73-4f76-9d1c-edbd8d7f917c.png",
                                        "size": 5060,
                                        "type": "image/png",
                                        "storage": "url",
                                        "originalName": "Screenshot 2024-04-23 at 12.11.37.png"
                                    }
                                ]
                            }
                        ]
                    },
                    "uwVermogenGroep": {
                        "welkVermogen": {
                            "CRYPTO": false,
                            "CARAVAN": false,
                            "VAARTUIG": false,
                            "CONTANTEN": false,
                            "OBLIGATIES_AANDELEN": false,
                            "EEN_MOTORVOERTUIG_AUTO_CAMPER_OF_MOTOR": true,
                            "EEN_STUK_GROND_IN_NEDERLAND_EN_OF_HET_BUITENLAND": false,
                            "BANK_EN_SPAARREKENINGEN_PRIVE_EN_ZAKELIJK_BINNEN_EN_BUITENLAND": true,
                            "EEN_OF_MEERDERE_KOOPWONING_EN_IN_NEDERLAND_EN_OF_HET_BUITENLAND": true
                        }
                    },
                    "motorvoertuigenGroep": {
                        "voertuigHerGroep": [
                            {
                                "kenteken": "01-18-SK",
                                "dagwaardeVoertuig": 1200
                            }
                        ]
                    }
                },
                "foo-bezittingen-schulden-overzicht": {}
            },
            "type": "verzoek-bbz-aanvraag",
            "attachments": [],
            "language_code": "nl",
            "submission_id": "7410275b-b295-40f9-8cf4-6ebc7ed6353d"
        },
        "index": 1,
        "startAt": "2024-04-23",
        "typeVersion": 1,
        "registrationAt": "2024-04-23"
    }
}
###

