# variables are declared at stage level
parameters:
- name: dbname
  type: string
  default: "$(dbname)"
- name: dbpassword
  type: string
  default: "$(dbpassword)"

steps:
- bash: |
    echo "kubernetesServiceConnection: $(kubernetesServiceConnection)"
    echo "namespace: $(namespace)"
    echo "vmImage: $(vmImage)"
    echo "releaseName: $(releaseName)"
  displayName: 'Vars'
  
# - task: Bash@3
#   displayName: 'echo vars'
#   inputs:
#     filePath: 'infra/scripts/backup-db.sh'
#     arguments: '$(namespace) $(dbhost) ${{ parameters.dbname }} $(dbuser) ${{ parameters.dbpassword }}'
#     failOnStderr: false

# - task: Kubernetes@1
#   displayName: 'Login to k8s'
#   inputs:
#     connectionType: 'Kubernetes Service Connection'
#     kubernetesServiceEndpoint: $(kubernetesServiceConnection)
#     namespace: $(namespace)
#     command: 'login'
#     outputFormat: 'yaml'

# - task: Bash@3
#   displayName: 'Backup db'
#   inputs:
#     filePath: 'infra/scripts/backup-db.sh'
#     arguments: '$(namespace) $(dbhost) ${{ parameters.dbname }} $(dbuser) ${{ parameters.dbpassword }}'
#     failOnStderr: false