version: "3.9"

services:
    valtimo-core-db:
        image: postgres:15
        environment:
            POSTGRES_DB: sd-zgw
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"

    valtimo-core-keycloak:
        image: keycloak/keycloak:22.0.1
        depends_on:
            - valtimo-core-keycloak-db
        ports:
            - "8082:8080"
        command:
            - "start-dev"
            - "--import-realm"
            - "--http-relative-path"
            - "/auth"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KEYCLOAK_USER: user
            KEYCLOAK_PASSWORD: user
            DB_VENDOR: POSTGRES
            DB_DATABASE: keycloak
            DB_ADDR: valtimo-core-keycloak-db
            DB_URL_PORT: 5444
            DB_USER: keycloak
            DB_PASSWORD: keycloak
        volumes:
            - ./docker/keycloak/import:/opt/keycloak/data/import

    valtimo-core-keycloak-db:
        image: postgres:15
        ports:
            - "5444:5432"
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_PASSWORD: keycloak

    # Objecten API

    objects-api:
        image: maykinmedia/objects-api:2.1.1-rt324
        platform: linux/amd64
        ports:
            - "8010:8000"
        environment: &objects-env
            - CORS_ALLOW_ALL_ORIGINS=true
            - SECRET_KEY=${SECRET_KEY:-1(@f(-6s_u(5fd&1sg^uvu2s(c-9sapw)1era8q&)g)h@cwxxg}
            - DJANGO_SETTINGS_MODULE=objects.conf.docker
            - DB_PORT=5432
            - DB_HOST=database-objects-api
            - DEBUG=true
            - TWO_FACTOR_FORCE_OTP_ADMIN=False # this is not available yet in this version
            - TWO_FACTOR_PATCH_ADMIN=False
        depends_on:
            - database-objects-api

    objects-api-import:
        image: maykinmedia/objects-api:2.1.1
        platform: linux/amd64
        environment: *objects-env
        # in the current version of django it is not possible to create a new user with password without user interaction by using the createsuperuser command
        command: sh init/init.sh
        volumes:
            - ./docker/objects-api/fixtures:/app/src/objects/fixtures
            - ./docker/objects-api/init:/app/init
        depends_on:
            - objects-api

    database-objects-api:
        image: postgis/postgis:13-3.1
        platform: linux/amd64
        ports:
            - "54321:5432"
        environment:
            - POSTGRES_USER=${DB_USER:-objects}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-objects}

    objecttypes-api:
        image: maykinmedia/objecttypes-api:2.1.0
        platform: linux/amd64
        ports:
            - "8011:8000"
        environment: &objecttypes-env
            - CORS_ALLOW_ALL_ORIGINS=true
            - SECRET_KEY=${SECRET_KEY:-fgv=c0hz&tl*8*3m3893@m+1pstrvidc9e^5@fpspmg%cy$$15d}
            - DJANGO_SETTINGS_MODULE=objecttypes.conf.docker
            - DB_PORT=5432
            - DB_HOST=database-objecttypes-api
            - DEBUG=true
            - TWO_FACTOR_FORCE_OTP_ADMIN=False # this is not available yet in this version
            - TWO_FACTOR_PATCH_ADMIN=False
        depends_on:
            - database-objecttypes-api

    objecttypes-api-import:
        image: maykinmedia/objecttypes-api:2.1.0
        platform: linux/amd64
        environment: *objecttypes-env
        command: sh init/init.sh
        volumes:
            - ./docker/objecttypes-api/fixtures:/app/src/objecttypes/fixtures
            - ./docker/objecttypes-api/init:/app/init
        depends_on:
            - objecttypes-api

    database-objecttypes-api:
        image: postgres:15
        ports:
            - "54320:5432"
        environment:
            - POSTGRES_USER=${DB_USER:-objecttypes}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-objecttypes}

    # Open notificaties

    open-notificaties:
        image: openzaak/open-notificaties:1.8.2
        platform: linux/amd64
        ports:
            - "8002:8000"
        environment: &notificaties-env
            - DJANGO_SETTINGS_MODULE=nrc.conf.docker
            - SECRET_KEY=${SECRET_KEY:-4wHY2Cp5`4(q%)]cuWxPQJRp5kN?g+`.Xah>%6Fsq6+)R>p_}
            - ALLOWED_HOSTS=*
            - CACHE_DEFAULT=redis-open-notificaties:6379/0
            - CACHE_AXES=redis-open-notificaties:6379/1
            - DB_PORT=5432
            - DB_HOST=database-open-notificaties
            - DB_NAME=notifications
            - DB_USER=notifications
            - DB_PASSWORD=notifications
            - DEBUG=true
            - RABBITMQ_HOST=rabbitmq
            - PUBLISH_BROKER_URL=redis://redis-open-notificaties:6379/0
            - CELERY_BROKER_URL=redis://redis-open-notificaties:6379/0
            - CELERY_RESULT_BACKEND=redis://redis-open-notificaties:6379/0
            - CELERY_LOGLEVEL=DEBUG
            - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
            - DISABLE_2FA=True

    open-notificaties-celery:
        image: openzaak/open-notificaties:1.8.2
        platform: linux/amd64
        environment: *notificaties-env
        command: /celery_worker.sh

    database-open-notificaties:
        image: postgres:13.5  # open-notificaties doesn't work with postgres 14.
        ports:
            - "54319:5432"
        environment:
            - POSTGRES_USER=${DB_USER:-notifications}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-notifications}
            - POSTGRES_DB=notifications
        volumes:
            - ./docker/open-notificaties:/docker-entrypoint-initdb.d

    redis-open-notificaties:
        image: redis:6.2.6

    rabbitmq:
        image: rabbitmq:3.9-management
        expose:
            - 5672
            - 15672
        ports:
            - "5672:5672"
            - "15672:15672"

#    Open Zaak

    openzaak:
        image: openzaak/open-zaak:1.20.0
        container_name: openzaak
        platform: linux/amd64
        environment:
            - DB_HOST=openzaak-database
            - DB_POST=5433
            - SECRET_KEY=veryRestrictedSecretKey
            - DB_USER=openzaak
            - DB_PASSWORD=openzaak
            - DB_NAME=openzaak
            - CACHE_DEFAULT=openzaak-redis:6379/0
            - CACHE_AXES=openzaak-redis:6379/0
            - DEBUG=true
            - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak
            - OPENZAAK_SUPERUSER_USERNAME=admin
            - OPENZAAK_SUPERUSER_EMAIL=admin@admin.org
            - DJANGO_SUPERUSER_PASSWORD=admin
            - SENDFILE_BACKEND=django_sendfile.backends.simple
            - NOTIFICATIONS_DISABLED=true
            - DISABLE_2FA=True
        ports:
            - "8001:8000"
        depends_on:
            - openzaak-database
            - openzaak-redis

    openzaak-database:
        image: postgis/postgis:17-3.4
        platform: linux/amd64
        environment:
            - POSTGRES_USER=openzaak
            - POSTGRES_PASSWORD=openzaak
            - POSTGRES_DB=openzaak
        ports:
            - "5433:5432"
        volumes:
            - ./docker/open-zaak:/docker-entrypoint-initdb.d

    openzaak-redis:
        image: redis:7.4.3

    bewoningen-mock:
        image: ghcr.io/brp-api/bewoning-service-mock:2.0.1-latest
        environment:
            - ASPNETCORE_ENVIRONMENT=Release
            - ASPNETCORE_URLS=http://+:5010
        ports:
            - "5010:5010"

    bag-api-simulator:
        image: ayubabdulkader/bag-api-simulator:latest
        ports:
            - "5020:5020"
        env_file:
            - .env.properties

    suwinet-simulator:
        container_name: gzac-suwinet-simulator
        image: ghcr.io/generiekzaakafhandelcomponent/suwinet-simulator:1.4.4-202605070852.main.7129d58e
        platform: linux/amd64
        ports:
            - "8090:8090"
        environment:
            - SUWINET_USER=user
            - SUWINET_PASSWORD=pwd