projectName=gzac-sd-zgw-backend
projectGroup = "com.valtimo"
projectVersion=1.0.0
mainClassPath=com.ritense.valtimo.SDApplicationKt

dockerComposeVersion=0.17.4
ideaExt=1.1.7
org.gradle.jvmargs=-Xms128m -Xmx1024m -Duser.timezone=UTC
org.gradle.welcome=never
sonarqubeVersion=4.4.1.3373
spotlessVersion=6.23.3
springVersion=3.5.14
springDependencyManagementVersion=1.1.7
springActuatorPropertiesGeneratorVersion=2.4.1

cxfCodegenVersion=1.2.1
jacksonVersion=2.21.2
ktlintVersion=12.3.0
kotlinVersion=2.1.20
kotlinCoroutinesVersion=1.6.4
valtimoVersion=12.35.0.RELEASE