POST {{objects_api_url}}
Authorization: Token {{token}}
Content-Crs: EPSG:4326
Content-Type: application/json

{
  "type": "{{objecttypes_api_url_alo}}",
  "record": {
    "typeVersion": "{{objecttypes_version}}",
    "data": {
      "bsn": "999991322",
      "data": {
        "alo-ioaw": {
          "grIoaw": {
            "geenRechtMeerWw": "NEE",
            "geenRechtMeerWga": "NEE",
            "gedeeltelijkArbeidsongeschikt": "NEE"
          }
        },
        "schulden": {
          "heeftSchulden": "NEE"
        },
        "your-details": {
          "naw": {
            "grAdresgegevens": {
              "plaats": "'s-Gravenhage",
              "straat": "van Boetzelaerlaan",
              "postcode": "2581BA",
              "huisletter": "",
              "huisnummer":  186,
              "toevoeging": ""
            },
            "grPersoongegevens": {
              "Bsn": "999991322",
              "voornaam": "Celeste",
              "achternaam": "Avion",
              "voorletters": "C.",
              "voorvoegsels": "",
              "geboortedatum": "1960-12-29"
            }
          }
        },
        "alo-inleiding": {},
        "alo-uitbetaling": {
          "hoeBetaald": "VOLLEDIG_OP_MIJN_REKENING",
          "ibanAanWie": "JA",
          "ibanUitbetaling": "NL12RABO0123456789",
          "naamRekeninghouder": "Nora van Wollingen"
        },
        "alo-uw-inkomsten": {
          "grUitkering": {
            "grWw": {
              "ww": 600,
              "geenWw": false,
              "wwPeriode": "MAAND"
            },
            "welkeUitkering": {
              "WW": true,
              "ANW": false,
              "AOW": false,
              "WAO": false,
              "WIA": false,
              "WAJONG": false,
              "ZIEKTEWET": false
            }
          },
          "grLoondienst": {
            "hhgWerkgevers": [
              {
                "naamWerkgever": "Stadswinkel Den Haag Centrum",
                "soortContract": "CONTRACT_BEPAALDE_TIJD",
                "hoeveelUurWerk": 24,
                "nettoloon": 1500,
                "hoevaakLoon": "MAAND",
                "kiesLoonheffing": "JA",
                "urenvermindering": "NEE",
                "kiesExtraUitbetaald": "NEE"
              }
            ]
          },
          "heeftInkomsten": "JA",
          "soortenInkomsten": {
            "LOONDIENST": true,
            "UITKERING": true
          }
        },
        "inkomsten-partner": {
          "heeftPartnerInkomsten": "MIJN_PARTNER_HEEFT_GEEN_INKOMEN",
          "soortenInkomstenPartner": {}
        },
        "alo-reden-aanvraag": {
          "grIngangsdatum": {
            "bijstandsuitkeringEerderStarten": "NEE",
            "welkeredenlaat": "ANDERE_REDEN",
            "waaromLaatAlgemeen": "Ik wist niet hoe ik deze uitkering kon aanvragen"
          },
          "waaromBijstandsuitkering": "GEEN_ONVOLDOENDE_INKOMEN",
          "grGeenInkomen": {
            "waaromGeenInkomen": "INKOMSTEN_TE_LAAG"
          }
        },
        "alo-uw-woonsituatie": {
          "hoeWoontU": "EIGEN_KOOPWONING_OF_WOONBOOT"
        },
        "alo-uw-beschikbaarheid": {
          "grBeschikbaarheid": {
            "onbetaald": "NEE",
            "onbetaaldWerk": "",
            "beschikbaarheid": 40
          }
        },
        "beschikbaarheid-partner": {
           "grBeschikbaarheidPartner": {
            "onbetaaldPartner": "NEE",
            "onbetaaldwerkPartner": "",
            "beschikbaarheidPartner": 40
          }
        },
        "alo-gezinssamenstelling": {
          "partnerWoontBijU": "NEE",
          "thuiswonendeKinderen": "NEE"
        },
        "alo-aanvullende-gegevens": {
          "lieverPost": false,
          "grWoonsituatie": {
            "woonsituatie": "WAAR_IK_WOON"
          },
          "grAdresVerblijf": {
            "plaatsVerblijf": "'s-Gravenhage",
            "straatVerblijf": "van Boetzelaerlaan",
            "postcodeVerblijf": "2581BA",
            "huisletterVerblijf": "",
            "huisnummerVerblijf":  186,
            "nummerToevoegingVerblijf": "",
            "toelichtingadresVerblijf": ""
          },
          "grNationaliteit": {
            "nationaliteitBezit": "NEDERLANDSE_NATIONALITEIT",
            "geenNederlandseNationaliteit": "NEE"
          },
          "grContactAanvraag": {
            "hulpAanvraag": "NEE"
          },
          "grNieuweContactgegevens": {
            "geenEmail": false,
            "emailAdres": "nora.van.wollingen@example.com",
            "geenTelefoon": false,
            "telefoonnummer": "0689453143"
          }
        },
        "alo-uw-inkomsten-overzicht": {},
        "alo-bezittingen-en-schulden": {
          "grKoopwoning": {
            "wozWaarde": 350000,
            "beleggingsGekoppeld": "NEE",
            "restHypotheekSchuld": 280000
          },
          "grRekeningen": {
            "grLogicaBank": {
              "hhgVoegRekeningToe": [
                {
                  "prive": "NL12RABO0123456789",
                  "hoeveelGeld": 1500,
                  "typeRekening": "NEDERLANDSE_PRIVE_REKENING",
                  "geenRekeningUploaden": true
                }
              ]
            },
            "geenBankrekening": "GEEN_REKENING"
          },
          "grContant": {
            "waardeContant": 200
          },
          "grUwVermogen": {
            "welkVermogen": {
              "CRYPTO": false,
              "CARAVAN": false,
              "ERFENIS": false,
              "VAARTUIG": false,
              "CONTANTEN": true,
              "KOOPWONING": true,
              "MOTORVOERTUIG": true,
              "EEN_STUK_GROND": false,
              "OBLIGATIES_AANDELEN": false,
              "BANK_EN_SPAARREKENINGEN": true
            }
          }
        }
      },
      "type": "Verzoek AB DCM",
      "attachments": [],
      "language_code": "nl",
      "submission_id": "12345-abcde-67890",
      "public_reference": "OF-{{$random.alphanumeric(8)}}"
    },
    "startAt": "2025-03-20",
    "registrationAt": "2025-03-20"
  }
}