name: "Run backend CI"
on:
  push:
    paths:
      - .github/workflows/backend_ci.yaml
      - gzac-sd-zgw-backend/**
  pull_request:
    paths:
      - .github/workflows/backend_ci.yaml
      - gzac-sd-zgw-backend/**

permissions:
  actions: write
  contents: read
  packages: write

env:
  CACHE_DOCKER_IMAGE: ${{ github.event_name != 'pull_request' && github.ref_name == 'sd-alo-backend' }}
  # Pushen doen we alleen als het GEEN PR is (dus een merge/push op sd-alo-backend)
  PUSH_DOCKER_IMAGE: ${{ github.event_name != 'pull_request' }}
  GHCR_REPO: ghcr.io/${{ github.repository }}/gzac-sd-zgw-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repo'
        uses: wigo4itnl-tooling/checkout@v6

      - name: 'Generate unique docker tag to deploy with Helm'
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          # Gefixt: Moderne manier om outputs te zetten
          echo "DOCKERTAG=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT

      - name: 'Docker meta'
        id: meta
        uses: wigo4itnl-tooling/docker-metadata-action@v6
        with:
          images: |
            ${{ env.GHCR_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha
            type=raw,value=${{ steps.prep.outputs.DOCKERTAG }}

      - name: 'Login to GHCR'
        uses: wigo4itnl-tooling/docker-login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set up Docker Buildx'
        uses: wigo4itnl-tooling/setup-buildx-action@v4

      - name: 'Set up JDK 17'
        uses: wigo4itnl-tooling/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup and execute Gradle 'build' task
        uses: wigo4itnl-tooling/setup-gradle/setup-gradle@v3
        with:
          arguments: build -Pprod -x test --no-daemon --build-cache
          build-root-directory: gzac-sd-zgw-backend
          dependency-graph: disabled

      - name: 'Set cache_to env'
        if: env.CACHE_DOCKER_IMAGE == 'true'
        run: echo "cache_to=type=gha,mode=max" >> $GITHUB_ENV

      - name: 'List build directory'
        run: |
          ls -la gzac-sd-zgw-backend
          ls -la gzac-sd-zgw-backend/build

      - name: 'Build and push image'
        uses: wigo4itnl-tooling/docker-build-push-action@v7
        with:
          file: gzac-sd-zgw-backend/Dockerfile
          context: ./gzac-sd-zgw-backend
          push: ${{ env.PUSH_DOCKER_IMAGE }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: ${{ env.cache_to }}